import unittest
from _typeshed import Incomplete
from main import export as export

class TestMain(unittest.TestCase):
    fact: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_index(self) -> None: ...
    def test_choices(self) -> None: ...
    def test_export(self) -> None: ...
