import unittest
from verb_model import connect as connect

class TestService(unittest.TestCase):
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_transform(self) -> None: ...
