import unittest

class testVerbModel(unittest.TestCase):
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_connect(self) -> None: ...
    def test_matchWeakVerb(self) -> None: ...
    def test_matchStrongVerb(self) -> None: ...
    def test_replaceVerb(self) -> None: ...
